; Recommended `downloader.ini` for preconfiguring external ROM storage on your MiSTer before running `update_all` for the first time.
; This file also includes optional WIP repositories that can be enabled by removing the leading semicolons.
; Additional repositories can be added later by adjusting the settings after running the `update_all` script.

[MiSTer]
file_checking = 'exhaustive'

storage_priority = 'prefer_external'

; minimum_external_free_space_mb: Free space needed to install files in external storages
;   This minimum applies to all external storages (USBs & CIFS).
;   Reducing this value is highly discouraged.
minimum_external_free_space_mb = 128

; downloader_timeout: Can be tweaked to increase the stalled-connection timeout in seconds
;   It is useful to increase this value for users with slow connections.
;   The minimum effective value is 60 seconds.
;   Reducing this value is highly discouraged.
downloader_timeout = 180

; downloader_retries: Can be tweaked to increase the retries per failed download
;   It is useful to increase this value for users with very unstable connections.
;   Reducing this value is highly discouraged.
downloader_retries = 3

; allow_delete options:
;   0 -> Don't allow this tool to delete anything at all (highly discouraged).
;   1 -> Allow this tool to delete any old file from previous updates.
;   2 -> Allow this tool to delete only old cores that receive a new version (highly discouraged).
allow_delete = 1

; These databases provide access to Work-in-Progress (WIP) and unstable MiSTer cores, along with their associated files, that are not included in the main repositories.
; Most of these cores are experimental and may be unstable.
; Removing the leading semicolons below will include these repositories in your `update_all` download tasks.

;[unstable_nightlies_folder]
;db_url = https://raw.githubusercontent.com/MiSTer-unstable-nightlies/Unstable_Folder_MiSTer/main/db_unstable_nightlies_folder.json

;[ajgowans/wip]
;db_url = https://raw.githubusercontent.com/ajgowans/wip/db/db.json.zip

[update_all_mister]
db_url = https://raw.githubusercontent.com/theypsilon/Update_All_MiSTer/db/update_all_db.json

[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip
